name: Build Test Deploy CI/CD Sample

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    name: Build, Test, and Deploy APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Archive APK
      uses: actions/upload-artifact@v2.2.4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk
