# script For Creating Debug Build 

name: Gradel Publish
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Archive APK
      uses: actions/upload-artifact@v2
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk
        distribution: 'untracked'

