name: Sample Action For CI/CD Workflow

on:
  push:
    branches:
      - main # Trigger this workflow on push events to the main branch
  pull_request:
    branches:
      - main # Trigger this workflow on pull requests targeting the main branch

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # This action checks out the code from the repository.

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
      # This action sets up JDK 17 to build a Java-based project.

    - name: Install dependencies
      run: npm install
      # This action installs project dependencies (for Node.js-based projects).

    - name: Build
      run: ./gradlew build
      # This action builds the project (for Gradle-based projects).

    - name: Run Unit Tests
      run: npm test
      # This action runs unit tests (for Node.js-based projects).

    - name: Run Android Tests
      run: ./gradlew test
      # This action runs Android tests (for Android projects).
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Archive APK
      uses: actions/upload-artifact@v3
      
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk
      
 
