name: Sample Action For CI/CD Workflow

on:
  push:
    branches:
      - main
      - production_sample_branch_v1
      - regreesion_test_v2

jobs:
  build-test-deploy:
    name: Build, Test, and Deploy APK
    runs-on: ubuntu-latest

    steps:
    # Your existing build, test, and deploy steps here
    # ...

  update-production:
    name: Update Production Sample Branch
    runs-on: ubuntu-latest

    needs: build-test-deploy

    steps:
    - name: Checkout production Sample branch
      uses: actions/checkout@v3
      with:
        ref: production_sample_branch_v1
        path: production_sample_branch_v1  # The path where the branch will be checked out

    - name: Configure Git Merge Tool
      run: |
        git config --global merge.tool vscode
        git config --global mergetool.vscode.cmd "code --wait $MERGED"

    - name: Merge regreesion_test_v2 into production_sample_branch_v1
      run: |
        cd production_sample_branch_v1  # Change directory to the checked-out production branch
        git merge regreesion_test_v2 --no-commit  # Merge changes from regreesion_test_v2 into the production_sample_branch_v1

    - name: Commit changes
      run: git commit -m "Merge regreesion_test_v2 into production_sample_branch_v1"

    - name: Push changes
      run: git push origin production_sample_branch_v1
